

development:

  CONSUMER_API_KEY = <%= ENV["CONSUMER_API_KEY"]%>
  CONSUMER_API_SECRET = <%= ENV["CONSUMER_API_SECRET"]%>

  ACCESS_TOKEN = <%= ENV["ACCESS_TOKEN"]%>
  ACCESS_TOKEN_SECRET = <%= ENV["ACCESS_TOKEN_SECRET"]%>


production:

  CONSUMER_API_KEY = <%= ENV["CONSUMER_API_KEY"]%>
  CONSUMER_API_SECRET = <%= ENV["CONSUMER_API_SECRET"]%>

  ACCESS_TOKEN = <%= ENV["ACCESS_TOKEN"]%>
  ACCESS_TOKEN_SECRET = <%= ENV["ACCESS_TOKEN_SECRET"]%>
